#!/bin/sh

mount -t tmpfs -o size=30M tmpfs /tmp/
# Временно здесь
#mount -n -t ext3 -o remount,defaults,ro /dev/mmcblk0p2 /

cd /start
./can

mkdir /media/log

export BIN_DIR=/media/bin
export DAT_DIR=/media/dat
export TMP_DIR=/tmp
export LOG_DIR=/media/log

cd $DAT_DIR/Bootloader/
$BIN_DIR/Bootloader/master-start

# 
# ./monitor-start &
# sleep 10
# ./map-start &

exit 0

