#!/bin/sh
#
# Start user application...
#

case "$1" in
  start)
 	echo "Mount /proc /sys /dev fs..."
	mount -t proc proc /proc
	mount -t sysfs sys /sys
	mount -t tmpfs mdev /dev
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

