#!/bin/sh
#
# Start user application...
#

case "$1" in
  start)
 	echo "Mount /, /media, /tmp fs..."
#	mount -n -t ext3 -o remount,defaults,ro /dev/mmcblk0p2 /
	if [ -e /dev/mmcblk0p1 ]; then
		mount -t vfat -o sync,noatime,nodiratime /dev/mmcblk0p1 /media
	else
		mount -t yaffs /dev/mtdblock4 /media
	fi
	mount -t tmpfs -o size=30M tmpfs /tmp/
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

