#!/bin/sh
#
# Start user application...
#

case "$1" in
  start)
 	echo "Starting user applications..."
	/start/starter
	;;
  stop)
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

